ignores = [
    "*.o",
    "*.obj",
    "*.d",
    "*.slo",
    "*.lo",
    "*.gch",
    "*.pch",
    "*.lai",
    "*.la",
    "/build*/",
    "/Debug/",
    "/Release/",
    "/compile_commands.json",
    "/.clangd/",
    "*.dSYM/",
    "/CMakeFiles/",
    "/CMakeScripts/",
    "/Testing/",
    "/cmake-build-*/",
    "CMakeCache.txt",
    "cmake_install.cmake",
]
