ignores = [
    "/node_modules/",
    "/.npm/",
    "/.yarn/",
    "*.min.js",
    "*.min.css",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "/coverage/",
    "/.nyc_output/",
    "/.next/",
    "/.nuxt/",
    "/out/",
    "/.cache/",
    "/storybook-static/",
    ".eslintcache",
    "/dist/",
    "/build/",
    "/.parcel-cache/",
    "/.turbo/",
    "bun.lock",
]
