ignores = [
    "*.class",
    "*.jar",
    "*.war",
    "*.ear",
    "*.nar",
    "hs_err_pid*",
    "/target/",
    "/.mvn/",
    "/gradle/",
    "/.gradle/",
    "/out/",
    "/build/",
    "/.settings/",
    "/.project",
    "/.classpath",
    "/.apt_generated/",
    "/.factorypath",
    "gradlew",
    "gradlew.bat",
]
