ignores = [
    "/__pycache__/",
    "*.py[cod]",
    "*$py.class",
    "/.env/",
    "/.venv/",
    "/venv/",
    "/.python-version",
    "/.pytest_cache/",
    "/.coverage",
    "/htmlcov/",
    "/.tox/",
    "/.eggs/",
    "/.ipynb_checkpoints/",
    "*.egg-info/",
    "/site/",
    "/.mypy_cache/",
    "/.ruff_cache/",
    "poetry.lock",
    "uv.lock",
]
